apiVersion: apps/v1
kind: Deployment
metadata:
  name: certstore-frontend
  namespace: karpatilabor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: certstore-frontend
  template:
    metadata:
      labels:
        app: certstore-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/zolmen/gde-alkfet/frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: certstore-frontend
  namespace: karpatilabor
spec:
  selector:
    app: certstore-frontend
  ports:
  - port: 80
    targetPort: 80