apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: certstore-ingress
  namespace: karpatilabor
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - karpatilabor.com
    - app.karpatilabor.com
    secretName: certstore-tls
  rules:
  - host: karpatilabor.com
    http:
      paths:
      - path: /api/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: certstore-backend
            port:
              number: 80
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: certstore-frontend
            port:
              number: 80
  - host: app.karpatilabor.com
    http:
      paths:
      - path: /api/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: certstore-backend
            port:
              number: 80
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: certstore-frontend
            port:
              number: 80