apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
images:
  - name: ghcr.io/zolmen/gde-alkfet/backend
    newTag: latest
  - name: ghcr.io/zolmen/gde-alkfet/frontend
    newTag: latest